### PR TITLE
Pull in old png Solidus logo

### PR DESCRIPTION
**Pull request by Sinetheta**
This PR makes us green with Solidus master.

The Solidus admin area was recently changed to use an svg logo https://github.com/solidusio/solidus/pull/2995 but that is not supported by Prawn so it broke the pdf embed here.

The old png logo is no longer used in Solidus so it's only a matter of time before someone removes it. As such I have pulled it in for use in the pdf header. I kept the same filename because I figured it less likely that the png logo ever be updated again in Solidus than maybe someone customized their Solidus install by overwriting the image instead of changing the config.

This has the unfortunate affect of no longer automatically following Solidus admin logo customizations, but I don't think it would be worth doing fancy svg detection at that point. We have our own config, folks can use that if needed.

### CODE REVIEW

**Comment by Sinetheta** [comment]
No problem @aitbw I was just taking a stab at greening up https://extensions.solidus.io/ 😆

**Comment by mdesantis** [comment]
What about leave the configuration possibility? With something like

```ruby
preference :print_invoice_logo_path, :string, :default => Spree::Config[:print_invoice_logo]
```

**Comment by aitbw** [comment]
@Sinetheta discussing this with @mdesantis, @spaghetticode, and @kennyadsl, I feel like we can improve this PR a little more: what do you think about a conditional to use the preference (if it's a PNG) or use the Solidus logo as a fallback —that way we won't break invoices with custom logos.

**Comment by aitbw** [comment]
Superseeded by #22. Thanks for your contribution anyway, @Sinetheta. Much appreciated. :bowing_man:

**Comment by Sinetheta** [comment]
👍 thanks guys, just happy to see a fix went it. Sorry I didn't see the notifications.

**Pull request closed without merging**
